### PR TITLE
Fallback namespace

### PR DESCRIPTION
**Pull request by SergeyMakarenko**

### CODE REVIEW

**Review by sazonovkirill — CHANGES_REQUESTED** [review]
I see that unit tests are not great here, so I suggest we start working in that direction.

Could you add a unit test for `SwiftDocumentContext` (which verifies fallback to plain java namespace among other things)?

Also, did you figure out what's the value of having such an option (given that it might bring some confusion)?

**Comment by SergeyMakarenko** [comment]
I created a followup task to extend tests. For this specific change there is new test for maven plugin to check that generated namespace matches expected one.

**Comment by SergeyMakarenko** [comment]
Also regarding value/possible confusion with this option. This is an optional feature which is turned off by default. So if that option is turned on we can assume that one knows what they are doing.

**Review by sazonovkirill — APPROVED** [review]
Ok for now, but let's talk separately about unit tests in general

**Pull request merged**
