### PR TITLE
Upgrade to Guice 4 and Java 8

### PR DESCRIPTION
**Pull request by cberner**

### CODE REVIEW

**Comment by electrum** [comment]
Can you switch Swift to Airbase?

**Comment by andrewcox** [comment]
Shouldn't we wait until 4 is final at least? What is the benefit to doing this now (while 4 is still beta)?

**Comment by electrum** [comment]
Guice 3 fails on Java 8 if there is an error: https://github.com/google/guice/issues/757

Guice 4 has been in beta for over a year and seems to be widely used.

**Comment by martint** [comment]
Guice 4 has been in beta since 7/31/2013 (It has historically move really slowly). At this point, I believe "beta" just means "APIs may change without notice", rather than a reflection of how robust it is.

**Comment by andrewcox** [comment]
Cool

**Comment by cberner** [comment]
Ok, updated to use airbase, @electrum

**Comment by andrewcox** [comment]
merged & pushed

**Pull request closed without merging**
