### PR TITLE
Recursive types

### PR DESCRIPTION
**Pull request by andrewcox**
Review for recursive types support in swift.

### CODE REVIEW

**Comment by andrewcox** [comment]
@alandau this is not finalized there are a couple things missing:

1) support for swift2thrift isn't finished yet so I haven't included any changes to that (except to keeping it compiling)
2) i still need to add a few unit tests where there is recursion that is traced through a collection element type is not direct: e.g. ( A contains a List<B>, and B contains an A ). And also tests to try building type metadata from different starting points (e.g. in a corecursive case where one ref is marked "isRecursive", I want test starting fresh from either type, right now I'm only testing starting from one part of the chain)

Point 1 will need some code changes and is necessary to put this all in without breaking swift2thrift, and point 2 will likely also involve code changes (besides just new tests) because I think there are some subtle differences between current behavior in this change and how recursion in fbthrift C++ works, so I'll need to fix those. Thus, these changes are not complete, but this is a fair bit of code changed, and it's already complete enough for you to start looking at.

**Comment by andrewcox** [comment]
Another TODO: support for IDL annotations on fields should include pushing these back out through swift2thrift. I'll update this shortly, I have the code already to do it but it was in the commit to make recursive types work with swift2thrift (not fully working yet). It doesn't really belong there though.

**Comment by alandau** [comment]
Like!
Several nits inline.
The bigger thing: Would like some explanation of how it works. Nothing big, just a couple sentences with the general idea.

**Comment by andrewcox** [comment]
@alandau these new commits address your comments, fix swift2thrift support, and add some new unit tests that expose problems I'd missed, and fix those problems.

**Comment by alandau** [comment]
lgtm

**Comment by andrewcox** [comment]
Rearranged the commits and squashed in fixes to the appropriate places, then merged

**Pull request closed without merging**
