### PR TITLE
Combine swift and nifty repositories

### PR DESCRIPTION
**Pull request by SergeyMakarenko**

### CODE REVIEW

**Comment by siyengar** [comment]
so good

**Review by dain — CHANGES_REQUESTED** [review]
Don't do this.  Swift and nifty are separate projects and should remain separate.

**Comment by ryantimwilson** [comment]
@dain What's the reasoning for making them separate projects? Currently we release them at the same time and it just makes the release process more painful.

**Comment by dain** [comment]
These projects have always been separate and should remain separate.  One is a serialization framework and the other is a wire protocol.  The fact that they are often released at the same time does not mean they have to be.

The real problem is that at some point there was a dependency created from swtift to nifty.  At the most this could be an optional dependency, but should really be redesigned so that there is a service interface that nifty can provide an implementation of, so that this code can once again be independent of the wire protocol implementation.

**Pull request closed without merging**
