### PR TITLE
Created maven plugin for swift2thrift and added support for Twitter Future

### PR DESCRIPTION
**Pull request by rojanu**
When using maven projects, creating thrift files manually doesn't make sense created a maven plugin to take care of this at the generate sources stage.

Also, Needed support for twitter Future when using swift within Finagle

### CODE REVIEW

**Comment by electrum** [comment]
Please add tests for this. See the other Maven plugin for an example.

**Comment by electrum** [comment]
Can you move the code indentation/formatting changes into a separate commit?

**Comment by rojanu** [comment]
Added tests and removed code formatting

**Comment by rojanu** [comment]
I read my last comment and it sounds like I am part of Finagle team.  Just to set the records straight I am not part of finagle but we use finagle and swift together

**Comment by andrewcox** [comment]
@rojanu are you still interested in getting swift2thrift-maven-plugin in? Looks like you removed it from the pull with the "Move swift2thrift-maven-plugin to https://github.com/rojanu/swift2thr..." commit.

**Comment by rojanu** [comment]
I moved it this PR has been open for so long, looks like Swift is not interested in it.  I believe the maven plugin will be very good addition to Swift.  I can create a different PR just solely for the swift2thrift-maven-plugin on its own??

**Comment by szantopeter** [comment]
Guys are you planning to merge this pull request? It seems to be really useful!

**Pull request closed without merging**
